version: '3.6'

volumes:
    pgmaster:
    pgslave1:
    pgslave2:
    pgslave3:
    backup:
    pgadmin:

services:
    pgmaster:
        volumes:
            - pgmaster:/var/lib/postgresql/data

    pgslave1:
        volumes:
            - pgslave1:/var/lib/postgresql/data

    pgslave2:
        volumes:
            - pgslave2:/var/lib/postgresql/data

    pgslave3:
        volumes:
            - pgslave3:/var/lib/postgresql/data

    backup:
        volumes:
            - backup:/var/backups

    pgadmin:
        volumes:
            - pgadmin:/var/lib/pgadmin/data
