version: '3.5'

volumes:
    pgmaster:
    pgslave1:
    pgslave2:
    pgslave3:
    backup:

services: 
  pgmaster:
    volumes:
      - pgmaster:/var/lib/postgresql/data

  pgslave1:
    volumes:
      - pgslave1:/var/lib/postgresql/data

  pgslave2:
    volumes:
      - pgslave2:/var/lib/postgresql/data

  pgslave3:
    volumes:
      - pgslave3:/var/lib/postgresql/data

  backup:
    deploy:
      labels:
        - traefik.frontend.rule=Host:backup.${SUBDOMAIN}.${DOMAIN}
        - traefik.frontend.passHostHeader=true
        - traefik.enable=true
        - traefik.port=80
        - traefik.tags=${TRAEFIK_PUBLIC_TAG}
        - traefik.docker.network=${TRAEFIK_PUBLIC_NETWORK}
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
    volumes:
      - backup:/var/backups

  pgpool:
    deploy:
      labels:
          - traefik.frontend.rule=Host:${SUBDOMAIN}.${DOMAIN}
          - traefik.frontend.passHostHeader=true
          - traefik.enable=true
          - traefik.port=5430
          - traefik.tags=${TRAEFIK_PUBLIC_TAG}
          - traefik.docker.network=${TRAEFIK_PUBLIC_NETWORK}
          # Traefik service that listens to HTTP
          - traefik.redirectorservice.frontend.entryPoints=http
          - traefik.redirectorservice.frontend.redirect.entryPoint=https
          # Traefik service that listens to HTTPS
          - traefik.webservice.frontend.entryPoints=https

  pgadmin:
    deploy:
      labels:
          - traefik.frontend.rule=Host:pgadmin.${SUBDOMAIN}.${DOMAIN}
          - traefik.frontend.passHostHeader=true
          - traefik.enable=true
          - traefik.port=80
          - traefik.tags=${TRAEFIK_PUBLIC_TAG}
          - traefik.docker.network=${TRAEFIK_PUBLIC_NETWORK}
          # Traefik service that listens to HTTP
          - traefik.redirectorservice.frontend.entryPoints=http
          - traefik.redirectorservice.frontend.redirect.entryPoint=https
          # Traefik service that listens to HTTPS
          - traefik.webservice.frontend.entryPoints=https
