version: '3.7'

volumes:
  pgmaster:
  pgslave1:
  # pgslave2:
  pgslave3:
  pgbackup:
  pgadmin:

services:
  pgmaster:
    volumes:
        - pgmaster:/var/lib/postgresql/data

  pgslave1:
    volumes:
      - pgslave1:/var/lib/postgresql/data

  # pgslave2:
  #   volumes:
  #     - pgslave2:/var/lib/postgresql/data

  pgslave3:
    volumes:
      - pgslave3:/var/lib/postgresql/data

  pgbackup:
    volumes:
      - pgbackup:/var/backups

  pgadmin:
    volumes:
      - pgadmin:/var/lib/pgadmin/data
