version: '3.6'

services:
    pgmaster:
        volumes:
            - ./ssh/:/tmp/.ssh/keys

    pgslave1:
        volumes:
            - ./ssh:/tmp/.ssh/keys

    pgslave3:
        volumes:
            - ./ssh:/tmp/.ssh/keys

    backup:
        volumes:
            - ./ssh:/tmp/.ssh/keys

    pgpool:
        volumes:
            - ./ssh:/tmp/.ssh/keys
