version: '3.7'

services: 

  pgbackup:
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=${TRAEFIK_PUBLIC_NETWORK}"
        - "traefik.tcp.routers.pgbackup.entrypoints=ssh"
        - "traefik.tcp.routers.pgbackup.rule=HostSNI(`*`)"
        - "traefik.tcp.services.pgbackup.loadbalancer.server.port=22"

  pgpool:
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=${TRAEFIK_PUBLIC_NETWORK}"
        - "traefik.tcp.routers.pgpool.entrypoints=pg"
        - "traefik.tcp.routers.pgpool.rule=HostSNI(`*`)"
        - "traefik.tcp.routers.pgpool.service=pgpool"
        - "traefik.tcp.services.pgpool.loadbalancer.server.port=5432"


  pgadmin:
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=${TRAEFIK_PUBLIC_NETWORK}"
        - "traefik.http.routers.pgadmin.entrypoints=websecure"
        - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.${SUBDOMAIN}.${DOMAIN}`)"
        - "traefik.http.routers.pgadmin.tls.certresolver=cloudflare"
        - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
