version: '3.6'

volumes:
    pgmaster:
    pgslave1:
    pgslave2:
    pgslave3:
    backup:

services:
    pgmaster:
        volumes:
            - pgmaster:/var/lib/postgresql/data
            - ./.ssh/keys:/tmp/.ssh/keys

    pgslave1:
        volumes:
            - pgslave1:/var/lib/postgresql/data
            - ./.ssh/keys:/tmp/.ssh/keys

    pgslave2:
        volumes:
            - pgslave2:/var/lib/postgresql/data
            - ./.ssh/keys:/tmp/.ssh/keys

    pgslave3:
        volumes:
            - pgslave3:/var/lib/postgresql/data
            - ./.ssh/keys:/tmp/.ssh/keys

    backup:
        volumes:
            - backup:/var/backups
            - ./.ssh/keys:/tmp/.ssh/keys

    pgpool:
        volumes:
            - ./.ssh/keys:/tmp/.ssh/keys
