version: '3.6'

services:
    pgmaster:
        environment:
            NODE_ID: 1 # Integer number of node (not required if can be extracted from NODE_NAME var, e.g. node-45 => 1045)
            NODE_NAME: node1 # Node name
            CLUSTER_NODE_NETWORK_NAME: pgmaster # (default: hostname of the node)
            
            PARTNER_NODES: "pgmaster,pgslave1,pgslave3"
            REPLICATION_PRIMARY_HOST: pgmaster # That should be ignored on the same node
            
            NODE_PRIORITY: 100  # (default: 100)
            SSH_ENABLE: 1
            #database we want to use for application
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
            CLEAN_OVER_REWIND: 0
            CONFIGS_DELIMITER_SYMBOL: ;
            CONFIGS: "listen_addresses:'*';max_replication_slots:5"
                                  # in format variable1:value1[,variable2:value2[,...]] if CONFIGS_DELIMITER_SYMBOL=, and CONFIGS_ASSIGNMENT_SYMBOL=:
                                  # used for pgpool.conf file
            #defaults:
            CLUSTER_NAME: pg_cluster # default is pg_cluster
            REPLICATION_DB: ${REPLICATION_DB}
            REPLICATION_USER: ${REPLICATION_USER}
            REPLICATION_PASSWORD: ${REPLICATION_PASSWORD}

    pgslave1:
        environment:
            NODE_ID: 2
            NODE_NAME: node2
            CLUSTER_NODE_NETWORK_NAME: pgslave1 # (default: hostname of the node)
            SSH_ENABLE: 1
            PARTNER_NODES: "pgmaster,pgslave1,pgslave3"
            REPLICATION_PRIMARY_HOST: pgmaster
            REPLICATION_DB: ${REPLICATION_DB}
            REPLICATION_USER: ${REPLICATION_USER}
            REPLICATION_PASSWORD: ${REPLICATION_PASSWORD}
            CLEAN_OVER_REWIND: 1
            CONFIGS_DELIMITER_SYMBOL: ;
            CONFIGS: "max_replication_slots:10" #some overrides

    # pgslave2:
    #     environment:
    #         NODE_ID: 3
    #         NODE_NAME: node3
    #         CLUSTER_NODE_NETWORK_NAME: pgslave2 # (default: hostname of the node)

    #         REPLICATION_PRIMARY_HOST: pgslave1 # I want to have cascade Streeming replication
    #         REPLICATION_DB: ${REPLICATION_DB}
    #         REPLICATION_USER: ${REPLICATION_USER}
    #         REPLICATION_PASSWORD: ${REPLICATION_PASSWORD}
    #         #USE_REPLICATION_SLOTS: 0
    #         CONFIGS_DELIMITER_SYMBOL: ;
    #         CONFIGS: "listen_addresses:'*'"

    pgslave3:
        environment:
            NODE_ID: 4
            NODE_NAME: node4
            CLUSTER_NODE_NETWORK_NAME: pgslave3 # (default: hostname of the node)
            SSH_ENABLE: 1
            PARTNER_NODES: "pgmaster,pgslave1,pgslave3"
            REPLICATION_PRIMARY_HOST: pgmaster
            REPLICATION_DB: ${REPLICATION_DB}
            REPLICATION_USER: ${REPLICATION_USER}
            REPLICATION_PASSWORD: ${REPLICATION_PASSWORD}
            NODE_PRIORITY: 200  # (default: 100)
            CLEAN_OVER_REWIND: 1
            CONFIGS_DELIMITER_SYMBOL: ;
            CONFIGS: "listen_addresses:'*'"

    pgbackup:
        environment:
            REPLICATION_HOST: ${REPLICATION_HOST}
            REPLICATION_DB: ${REPLICATION_DB}
            REPLICATION_USER: ${REPLICATION_USER}
            REPLICATION_PASSWORD: ${REPLICATION_PASSWORD}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
            SSH_ENABLE: 1
            BACKUP_SCHEDULE: "*/30 */5 * * *"

    pgpool:
        environment:
            PCP_USER: ${PCP_USER}
            PCP_PASSWORD: ${PCP_PASSWORD}
            WAIT_BACKEND_TIMEOUT: 60

            CHECK_USER: ${CHECK_USER}
            CHECK_PASSWORD: ${CHECK_PASSWORD}
            CHECK_PGCONNECT_TIMEOUT: 3 #timout for checking if primary node is healthy

            SSH_ENABLE: 1
            DB_USERS: ${POSTGRES_USER}:${POSTGRES_PASSWORD} # in format user:password[,user:password[...]]
            BACKENDS: "0:pgmaster:5432:1:/var/lib/postgresql/data:ALLOW_TO_FAILOVER,1:pgslave1::::,3:pgslave3::::"  #,2:pgslave2::::4:pgslave4::::
                      # in format num:host:port:weight:data_directory:flag[,...]
                      # defaults:
                      #   port: 5432
                      #   weight: 1
                      #   data_directory: /var/lib/postgresql/data
                      #   flag: ALLOW_TO_FAILOVER
            REQUIRE_MIN_BACKENDS: 1 # minimal number of backends to start pgpool (some might be unreachable)
            CONFIGS: "num_init_children:250,max_pool:4"
                      # in format variable1:value1[,variable2:value2[,...]] if CONFIGS_DELIMITER_SYMBOL=, and CONFIGS_ASSIGNMENT_SYMBOL=:
                      # used for pgpool.conf file

    pgadmin:
        image: dpage/pgadmin4
        depends_on:
            - pgpool
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
